### ISSUE TITLE
vscode 不识别组件

### ISSUE THREAD

**Issue by zhgweb** [zhousg/consult-patient-h5-vue3-ts-pinia-vant#5]
淑淑我是83期的一转眼也三年多了,目前遇到的问题是 vscode不识别组件vue3+ts+uniapp,包括自己写的那个components下的 通过正则去配置 也不行 vscode插件也使用volar ts也托管了 vue2的也禁用了 就是不好使 
0.src\components\HbcyPopup.vue
1. src\types\components.d.ts 下 
```ts
// src/types/components.d.ts 全局组件类型声明
import HbcyIconTitle from '@/components/HbcyIconTitle.vue'
import HbcyButton from '@/components/HbcyButton.vue'
import HbcyTitleText from '@/components/HbcyTitleText.vue'
import HbcyPopup from '@/components/HbcyPopup.vue'
declare module 'vue' {
  export interface GlobalComponents {
    HbcyIconTitle: typeof HbcyIconTitle
    HbcyButton: typeof HbcyButton
    HbcyTitleText: typeof HbcyTitleText
    HbcyPopup: typeof HbcyPopup
  }
}
```
declare module 'vue' 换成 @vue/runtime-core uniapp的组件就识别了 但是 自定义组件<hbcy-popup/>  这种就不识别只识别驼峰的
2. page.json
```json
{
	// 组件自动导入
	"easycom": {
		// 是否开启自动扫描 @/components/$1/$1.vue 组件
		"autoscan": true,
		"custom": {
			// uni-ui 规则如下配置
			"^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue",
			// 以 Hbcy 开头的组件，在 components 目录中查找
			"^Hbcy(.*)": "@/components/Hbcy$1.vue"
		}
	},
	}
```
网上根本查不到也不会查,vue3+ts就是找黑马要的你的课和b站看的uni那个 这个vscode问题 太苦恼了

**Comment by zhgweb** [comment]
![image](https://github.com/zhousg/consult-patient-h5-vue3-ts-pinia-vant/assets/53853784/fa50f4b5-2c52-466b-a8a1-b188ea9e785e)

**Comment by zhousg** [comment]
安装下 @vue/runtime-core 试试，不行发 tsconfig.json 看看

**Comment by zhgweb** [comment]
换成declare module '@vue/runtime-core' 然后 并且pnpm 安装这个之后  都识别了 但是 页面上不显示那个组件
![image](https://github.com/zhousg/consult-patient-h5-vue3-ts-pinia-vant/assets/53853784/42be9bd8-33cb-491a-88a2-4f3b1df0860c)

**Comment by zhgweb** [comment]
tsconfig.json文件
```json

{
  "extends": "@vue/tsconfig/tsconfig.json",
  "compilerOptions": {
    "sourceMap": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
    "lib": ["esnext", "dom"],
    "types": ["@dcloudio/types", "miniprogram-api-typings", "@uni-helper/uni-app-types","@uni-helper/uni-ui-types" ]
  },
  "vueCompilerOptions": {
    "nativeTags": ["block", "component", "template", "slot"]
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
}

```

**Comment by zhousg** [comment]
不会啊，报啥错了？vue @vue/runtime-core 都要安装

**Comment by zhgweb** [comment]
什么错都不报 declare module '@vue/runtime-core' { 配置之后 组件用大驼峰就可以使用 用小写的 虽然有高粱提示 但是页面没效果

**Comment by zhgweb** [comment]
比如说 这是一个公共标题
```vue
<HbcyTitleText title-text="公共标题" />
 ```
如果 我
```vue
 <hbcy-title-text titleText="基本信息" />
 ```
 就没效果 但是 我页面上 如果有一个使用了 大驼峰 其他的我在使用小写 就可以了 很奇怪

**Comment by zhousg** [comment]
这个和TS无关了吧，就一个组件这样？还是其他组件都是？不改成 runtime-core 就支持吗？

**Comment by zhousg** [comment]
`"^hbcy-(.*)": "@/components/Hbcy$1.vue"`  再加一条这个配置 page.json

**Comment by zhgweb** [comment]
1.不改成@vue/runtime-core 使用vue的话 组件颜色 包括uniapp的标签就是蓝色的
2.并且 <hbcy-icon-title /> 这种组件报错如下 (添加完^hbcy-(.*) 这个配置 且删掉原先的)
`[vite]: Rollup failed to resolve import "D:/workspace/BoxFrotend/branches/uni-vue3-ts/src/components/Hbcyicon-title.vue" from "D:/workspace/BoxFrotend/branches/uni-vue3-ts/src/pages/insurances/index.vue?vue&type=script&setup=true&lang.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
3. <hbcy-icon-title /> 组件 在vue模式 用大驼峰命名 并且共存两个配置 也不行
----------------------------------------
目前个人理解为 需要像uniapp一样 uni-popup-dialog 这样命名两个单词以上的 
4. components.d.ts 文件 替换成  declare module '@vue/runtime-core' 时 所有组件颜色均绿色了能识别到了
5. pages.json 添加
```json
			"^Hbcy(.*)": "@/components/Hbcy$1.vue",
			"^hbcy-(.*)": "@/components/Hbcy$1.vue"
```
时 使用<hbcy-icon-title /> 报错
`
[vite]: Rollup failed to resolve import "D:/workspace/BoxFrotend/branches/uni-vue3-ts/src/components/Hbcyicon-title.vue" from "D:/workspace/BoxFrotend/branches/uni-vue3-ts/src/pages/insurances/index.vue?vue&type=script&setup=true&lang.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external` 
`
使用大驼峰的时候不报错且能用(pages.json 两个都配置的情况)
6. pages.json  只配置了hbcy-(.*) 这个情况的时候 使用大驼峰无用 且 >2个单词以上的包上述错误
7.以上所述 每一次更改,均cart+shift+p 重新加载窗口了 且重新运行
给我的整体感觉就是 如果我在components 定义组件的时候 换成 hbcy-Icon-Title 然后 在 pages.json 中
"^hbcy-(.*)": "@/components/Hbcy-$1.vue"
再然后在 components.d.ts 中
```ts
import HbcyIconTitle from '@/components/Hbcy-Icon-Title.vue'
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HbcyIconTitle: typeof HbcyIconTitle
  }
}
```

**Comment by zhgweb** [comment]
目前以这种方式已解决 但是为什么不知道 懵逼 也谢谢淑淑帮我解决 不然我更懵
![image](https://github.com/zhousg/consult-patient-h5-vue3-ts-pinia-vant/assets/53853784/9e78b5f4-fce2-4597-b2af-e63c5151bb0e)
![image](https://github.com/zhousg/consult-patient-h5-vue3-ts-pinia-vant/assets/53853784/166c88a0-c9b8-489f-8da6-570e2899782d)
![image](https://github.com/zhousg/consult-patient-h5-vue3-ts-pinia-vant/assets/53853784/0ec9079f-c978-499d-a8a5-04715c0aa7d1)
![image](https://github.com/zhousg/consult-patient-h5-vue3-ts-pinia-vant/assets/53853784/e643992d-2769-4c26-8f9c-182c3bf0dcc8)
昨晚回去看到您回复但是我这边回复不过去,就通过vx加您了,但是没通过

**Comment by zhousg** [comment]
```js
"^Hbcy(.*)": "@/components/Hbcy$1.vue",
"^hbcy-(.*)": "@/components/Hbcy$1.vue"
```
我在本地以上两种加上，kebab-case  PascalCase 都支持哈，如果你配置好了一个自己的喜好就OK，我关了 issues 哈

1. 颜色变绿是vscode识别了类型，和组件解析无关
2. 组件不解析和组件自动导入规则有关系，组件命名也有关系
